---
title: "Advanced plotting"
author: "Lindsay Fisher"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../Output")
```

# Load Libraries

```{r}
library(here)
library(tidyverse)
library(palmerpenguins)
library(patchwork)
library(ggrepel)
library(gganimate)
library(magick)
```

## Make Plots using new packages

# Use Patchwork


```{r penguinpatch, warning=FALSE, echo=FALSE, message=FALSE}
p1<-penguins %>%
  ggplot(aes(x = body_mass_g, 
             y = bill_length_mm, 
             color = species))+
  geom_point()
p1

p2<-penguins %>%
  ggplot(aes(x = sex, 
             y = body_mass_g, 
             color = species))+
  geom_jitter(width = 0.2)
p2

p1+p2 + #puts plots next to eachother
  plot_layout(guides = 'collect')+
  plot_annotation(tag_levels = 'A')


p1/p2 + #puts one plot on top of the other
  plot_layout(guides = 'collect')+ #collects 2 legends to make one
  plot_annotation(tag_levels = 'A')#labels each with a letter
```

# Use ggrepel
```{r carrepel, echo=FALSE, warning=FALSE, message=FALSE}
#mtcars is already part of one of the packages
ggplot(mtcars, aes(x = wt, 
                   y = mpg, #miles per gallon
                   label = rownames(mtcars))) + #extracts the rownames
  geom_text() + # creates a text label
  geom_point(color = 'red')#makes it red

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_text_repel() + # repel them - can say what distance (helps for reading)
  geom_point(color = 'red')

ggplot(mtcars, aes(x = wt, 
                   y = mpg, 
                   label = rownames(mtcars))) +
  geom_label_repel() + # repel them - but makes each one a label(box)
  geom_point(color = 'red')

```

# Use gganimate
```{r, warning=FALSE, echo=FALSE, message=FALSE}
penguins %>% 
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()+
  transition_states(
     year, # what are we animating by year to year
     transition_length = 2, #The relative length of the transition. - 2 seconds
     state_length = 1 # The length of the pause between transitions - 1 second
   )+
  ease_aes("sine-in-out") +
  ggtitle('Year: {closest_state}')+
  anim_save(here("Week_8","Output","mypengiungif.gif"))
```
# Penguin picture with Plot

```{r, echo=FALSE}
penguin<-image_read("https://pngimg.com/uploads/penguin/pinguin_PNG9.png")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
penguins %>%
ggplot(aes(x = body_mass_g, 
            y = bill_depth_mm, 
            color = species)) +
  geom_point()+
  ggsave(here("Week_8","Output","penguinplot.png"))
```

```{r}
penplot<-image_read(here("Week_8","output","penguinplot.png"))
out <- image_composite(penplot, penguin, offset = "+70+30")
out
```

